package api.constant;

public enum ErrorCode {
    LOAN_CONSIDERATION,
    LOAN_ALREADY_APPROVED,
    TRY_LATER,
    ORDER_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    ORDER_IMPOSSIBLE_TO_DELETE,
    TARIFF_NOT_FOUND
}
